import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  navbar: {
    backgroundColor: "#048ED4",
    paddingVertical: 20,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navbarTitle: {
    color: "#048ED4",
    fontSize: 16,
    fontWeight: "bold",
    
  },
  navbarIcons: {
    flexDirection: "row",
    gap: 16,
    marginTop: 30,
  },
  headerBg: {
    height: 160,
    width: "100%",
    marginTop: -5,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 10,
  },
  headerImage: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0.55,
  },
  gradientOverlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
    headerContent: {
    zIndex: 10,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  title: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 30,
    textShadowColor: "#048ED4",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 3,
  },
  title2: {
    color: "#ffffff",
    fontSize: 34,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
    lineHeight: 30,
    textShadowColor: "#048ED4",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 3,
  },
  overlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "#048ED4",
    opacity: 0.45,
  },
  headerBienvenida: {
    color: "#048ED4",
    fontSize: 22,
    fontWeight: "700",
  },
  headerSub: {
    color: "#048ED4",
    fontSize: 22,
    fontWeight: "700",
    marginTop: -2,
  },
  headerApp: {
    color: "#048ED4",
    fontSize: 22,
    fontWeight: "700",
    marginTop: -2,
  },
  content: {
    paddingHorizontal: 24,
    marginTop: 14,
    alignItems: "center",
  },
  reminder: {
    width: "95%",
    backgroundColor: "#F8BABA",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C62828",
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  reminderTitle: {
    textAlign: "center",
    fontSize: 18,
    color: "#C62828",
    fontWeight: "800",
  },
  reminderText: {
    marginTop: 6,
    textAlign: "center",
    fontSize: 12,
    lineHeight: 18,
    color: "#C62828",
  },
  infoText: {
    marginTop: 22,
    textAlign: "center",
    fontSize: 13,
    color: "#048ED4",
    lineHeight: 18,
    paddingHorizontal: 10,
  },
  regButton: {
    marginTop: 20,
    backgroundColor: "#FFD75B",
    width: 170,
    height: 60,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#048ED4",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  regButtonText: {
    color: "#048ED4",
    fontWeight: "700",
    fontSize: 16,
    textAlign: "center",
    lineHeight: 18,
    textDecorationLine: "underline",
    textDecorationColor: "#048ED4",
  },
});
