import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E6F2FF",
  },
  header: {
    width: "100%",
    backgroundColor: "#0089E0",
    alignItems: "center",
    paddingVertical: 40,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 16,
  },
  divider: {
    width: 60,
    height: 2,
    backgroundColor: "#ffffff",
  },
  iconContainer: {
    marginTop: 16,
    width: 70,
    height: 70,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 35,
    borderWidth: 1,
    borderColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  icon: {
    fontSize: 36,
  },
  formContainer: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#FFB700",
    borderRadius: 16,
    width: "90%",
    maxWidth: 500,
    marginHorizontal: "auto",
    marginTop: 32,
    marginBottom: 40,
    paddingHorizontal: 24,
    paddingVertical: 24,
    alignSelf: "center",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  halfInput: {
    flex: 1,
  },
  label: {
    fontWeight: "600",
    color: "#333333",
    marginBottom: 6,
    fontSize: 14,
  },
  spacedLabel: {
    fontWeight: "600",
    color: "#333333",
    marginTop: 16,
    marginBottom: 6,
    fontSize: 14,
  },
  input: {
    backgroundColor: "#E8F4FF",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#000000",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#B9DCFA",
  },
  button: {
    backgroundColor: "#0089E0",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFB700",
    marginTop: 28,
    flexDirection: "row",
    justifyContent: "center",
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  loginLink: {
    textAlign: "center",
    color: "#0089E0",
    marginTop: 20,
    textDecorationLine: "underline",
    fontSize: 14,
    fontWeight: "500",
  },
});
