import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#CEEDFF",
    },
    header: {
        backgroundColor: "#048ED4",
        paddingVertical: 12,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    backButton: {
        left: 16,
        zIndex: 10,
        marginTop: 30,
    },
    headerTitle: {
        color: "#ffffff",
        fontSize: 20,
        fontWeight: "600",
        textAlign: "center",
        flex: 1,
    },
    content: {
        flex: 1,
        padding: 16,
    },
    solicitudCard: {
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderLeftWidth: 4,
        borderLeftColor: "#048ED4",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    studentName: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1F2937",
        marginBottom: 8,
    },
    infoRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 6,
    },
    label: {
        fontSize: 14,
        fontWeight: "600",
        color: "#6B7280",
    },
    value: {
        fontSize: 14,
        color: "#1F2937",
        fontWeight: "500",
    },
    description: {
        fontSize: 13,
        color: "#6B7280",
        marginTop: 8,
        fontStyle: "italic",
    },
    buttonContainer: {
        flexDirection: "row",
        gap: 12,
        marginTop: 16,
    },
    approveButton: {
        flex: 1,
        backgroundColor: "#10B981",
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    rejectButton: {
        flex: 1,
        backgroundColor: "#EF4444",
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    buttonText: {
        color: "#ffffff",
        fontWeight: "700",
        fontSize: 14,
    },
    emptyText: {
        textAlign: "center",
        color: "#6B7280",
        marginTop: 32,
        fontSize: 16,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: "#ffffff",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        paddingBottom: 30,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1F2937",
        marginBottom: 12,
    },
    textInput: {
        backgroundColor: "#F3F4F6",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#D1D5DB",
        padding: 12,
        marginBottom: 16,
        minHeight: 100,
        textAlignVertical: "top",
    },
    modalButtonContainer: {
        flexDirection: "row",
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: "#D1D5DB",
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    confirmButton: {
        flex: 1,
        backgroundColor: "#EF4444",
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
    },
    modalButtonText: {
        fontWeight: "700",
        fontSize: 14,
    },
});