import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E6F2FF",
    paddingVertical: 20,
  },
  header: {
    width: "100%",
    backgroundColor: "#0089E0",
    alignItems: "center",
    paddingVertical: 40,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
  divider: {
    marginTop: 8,
    width: 60,
    height: 2,
    backgroundColor: "#ffffff",
  },
  iconContainer: {
    marginTop: 16,
    width: 70,
    height: 70,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 35,
    borderWidth: 1,
    borderColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  icon: {
    fontSize: 32,
  },
  formContainer: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#FFB700",
    borderRadius: 12,
    width: "85%",
    marginTop: 32,
    marginBottom: 32,
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: "center",
  },
  instructionText: {
    color: "#666666",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 20,
  },
  label: {
    alignSelf: "flex-start",
    fontWeight: "600",
    color: "#000000",
    marginBottom: 8,
    width: "100%",
  },
  input: {
    width: "100%",
    backgroundColor: "#B9DCFA",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#000000",
    marginBottom: 20,
  },
  button: {
    backgroundColor: "#0089E0",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFB700",
    width: "100%",
    marginTop: 12,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  backLink: {
    textAlign: "center",
    color: "#0089E0",
    marginTop: 16,
    textDecorationLine: "underline",
    fontSize: 12,
  },
  successContainer: {
    backgroundColor: "#D4EDDA",
    borderWidth: 1,
    borderColor: "#28A745",
    borderRadius: 8,
    padding: 16,
    marginHorizontal: 20,
    marginTop: 20,
    alignItems: "center",
  },
  successText: {
    color: "#155724",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  tokenLabel: {
    color: "#155724",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 8,
  },
  tokenText: {
    color: "#155724",
    fontSize: 11,
    fontFamily: "monospace",
    backgroundColor: "#E8F5E9",
    padding: 8,
    borderRadius: 4,
    marginBottom: 8,
  },
  tokenCopyLink: {
    color: "#0089E0",
    fontSize: 12,
    fontWeight: "600",
    textDecorationLine: "underline",
    textAlign: "center",
  },
});
