import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  navbar: {
    backgroundColor: "#048ED4",
    paddingVertical: 20,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  blackNavbar: {
    backgroundColor: "#0f172a",
  },

  logo: {
    width: 100,
    height: 60,
    marginRight: 'auto',
  },

  navbarIcons: {
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
    marginBottom: 10,
  },
  headerBg: {
    height: 160,
    width: "100%",
    marginTop: -5,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 10,
  },
  headerImage: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0.55,
  },
  gradientOverlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  headerContent: {
    zIndex: 10,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  title: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 30,
    textShadowColor: "#048ED4",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 3,
  },
  blackTitle: {
    color: "white",
    textShadowColor: "black",
  },
  title2: {
    color: "#ffffff",
    fontSize: 34,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
    lineHeight: 30,
    textShadowColor: "#048ED4",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 3,
  },
  blackTitle2: {
    color: "white",
    textShadowColor: "black",
  },
  content: {
    paddingHorizontal: 24,
    marginTop: 14,
    alignItems: "center",
  },
  infoText: {
    marginTop: 22,
    textAlign: "center",
    fontSize: 13,
    color: "#048ED4",
    lineHeight: 18,
    paddingHorizontal: 10,
  },
  blackInfoText: {
    color: "white",
  },
  regButton: {
    marginTop: 20,
    backgroundColor: "#FFD75B",
    width: 170,
    height: 60,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#048ED4",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  blackRegButton: {
    backgroundColor: "#334155",
    shadowColor: "black",
    borderColor: "#475569",
    borderWidth: 2,
  },
  regButtonText: {
    color: "#048ED4",
    fontWeight: "700",
    fontSize: 16,
    textAlign: "center",
    lineHeight: 18,
    textDecorationLine: "underline",
    textDecorationColor: "#048ED4",
  },
  blackRegButtonText: {
    color: "white",
  },
});
