import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E6F2FF",
    alignItems: "center",
  },
  header: {
    width: "100%",
    backgroundColor: "#0089E0",
    alignItems: "center",
    paddingVertical: 40,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 16,
  },
  logoContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 50,
    height: 50,
    tintColor: "#0089E0",
  },
  formContainer: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#FFB700",
    borderRadius: 12,
    width: "85%",
    marginTop: 32,
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: "center",
  },
  userIconBg: {
    backgroundColor: "#E6F2FF",
    borderRadius: 999,
    padding: 10,
    marginBottom: 12,
  },
  userIcon: {
    width: 40,
    height: 40,
    tintColor: "#0089E0",
  },
  label: {
    alignSelf: "flex-start",
    fontWeight: "600",
    color: "#000000",
    marginTop: 8,
  },
  input: {
    width: "100%",
    backgroundColor: "#B9DCFA",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginTop: 4,
    color: "#000000",
  },
  forgotPassword: {
    alignSelf: "flex-start",
    fontSize: 12,
    color: "#444444",
    marginTop: 8,
    marginBottom: 16,
  },
  button: {
    backgroundColor: "#0089E0",
    paddingVertical: 12,
    paddingHorizontal: 60,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFB700",
    width: "100%",
    marginTop: 16,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
});